(function($){'use strict';const GERMANY=79,SPAIN=191;const $body=$('body');const footerDisclaimer=document.getElementById('footer-disclaimer');const disclaimerSettings={cookieHideDisclaimerName:'marketing_mini_disclaimer',cookieVisitorRegulationName:eToroWP.cookieVisitorRegulationName,cookieMarketingDesignatedRegulationIdName:eToroWP.cookieUserDesignatedRegulationName};const evt=new CustomEvent('ondischange',{});let disclaimerObj,header,headerHeightGlobal;const mini_mode_class='mini_mode';const etoro_disclaimers={alreadyInserted:false,setHeaderStyle:function(dis,headerDiv,topLineHeight){},refreshDisStyle:function(){requestAnimationFrame(function(){if(!disclaimerObj){return;}
headerHeightGlobal=(header)?header.offsetHeight:0;etoro_disclaimers.setHeaderStyle(disclaimerObj,header,headerHeightGlobal);window.dispatchEvent(evt);});},setHeaderSettings:function(){disclaimerObj=document.querySelector('.floating-disclaimer');if(!disclaimerObj){return;}
disclaimerObj.prevDisHeight=disclaimerObj.prevTopLineHeight=0;header=document.querySelector('.e-header');headerHeightGlobal=(header)?header.offsetHeight:0;etoro_disclaimers.setHeaderStyle(disclaimerObj,header,headerHeightGlobal);},getDisclaimers:function(eDisclaimers,type){const disArgs={country:eToroMarketingData.countryId,regulation:eToroMarketingData.regulationId,language:getCurrentLang()};if(typeof window.etoroDisclaimers.asset!=='undefined'){disArgs.asset=window.etoroDisclaimers.asset;}
let disclaimersPriorityOrder=[{name:'regulation_country_asset',key:'regulation___'+disArgs.regulation+
'$country___'+disArgs.country+'$asset___'+disArgs.asset,},{name:'regulation_country',key:'regulation___'+disArgs.regulation+
'$country___'+disArgs.country,},{name:'regulation_asset',key:'regulation___'+disArgs.regulation+
'$asset___'+disArgs.asset,},{name:'regulation',key:'regulation___'+disArgs.regulation,},{name:'default_fallback',key:'default_disclaimers',}];if(isUsaUkPage){disclaimersPriorityOrder=[{name:'us-uk_options_related_pages',key:'us-uk_disclaimers',}];}
for(const element of disclaimersPriorityOrder){if(typeof eDisclaimers[element.key]!=='undefined'){if((type==='footer'&&eDisclaimers[element.key].footer.length>0)||(type==='floating'&&typeof eDisclaimers[element.key].floating!=='undefined')){window.etoroDisclaimers.chosedDiclaimerRule=element.key;return eDisclaimers[element.key];}}}},set_css_max_footer_height:function(){footerDisclaimer.classList.remove('hidden');const usFooterInfo=document.querySelector('.us-footer-info');const usInfoHeight=(usFooterInfo)?usFooterInfo.getBoundingClientRect().height+40:0;document.body.style.setProperty('--max-footer-dis-height',(footerDisclaimer.getBoundingClientRect().height+usInfoHeight)+"px");},renderFooterDisclaimer:function(){const resizeObserver=new ResizeObserver(etoro_disclaimers.set_css_max_footer_height);resizeObserver.observe(document.body);const etDisclaimers=etoro_disclaimers.getDisclaimers(window.eDisclaimers,'footer');if(!etDisclaimers||window.etoroDisclaimers.dontReplace===true){etoro_disclaimers.set_css_max_footer_height();return;}
footerDisclaimer.innerHTML=etDisclaimers.footer;const paramStr=window.location.search.substring(1);const searchParams=new URLSearchParams(paramStr);if(searchParams.has("gc")){const blocksForRemove=footerDisclaimer.querySelectorAll('.'+searchParams.get("gc"));blocksForRemove.forEach((element)=>{element.remove();});}
etoro_disclaimers.set_css_max_footer_height();},renderPopupDisclaimer:function(etDisclaimers){const popupDisclaimer=document.getElementById("pop-up-new-domains__disclaimer");if(popupDisclaimer){popupDisclaimer.innerHTML=(typeof etDisclaimers.floating!=='string')?etDisclaimers.floating.textFull:etDisclaimers.floating;}},renderFloatingDisclaimer:function(){if(!(typeof eToroMarketingData.regulationId&&typeof eToroMarketingData)){return;}
if(eToroMarketingData.countryId===219&&!isUsaUkPage){return;}
const etDisclaimers=etoro_disclaimers.getDisclaimers(window.eDisclaimers,'floating');if(!etDisclaimers){return;}
if(etoro_disclaimers.isMoneyFlow()){return;}
etoro_disclaimers.insertFloatingDisclaimerHTML(etDisclaimers);document.body.classList.add('disclamer_visible');etoro_disclaimers.observeDisclaimerResize();etoro_disclaimers.renderPopupDisclaimer(etDisclaimers);},isMoneyFlow:function(){if(typeof URLSearchParams==='function'){const urlParams=new URLSearchParams(window.location.search);if(urlParams.get("product")==="card"){return true;}}
return false;},insertFloatingDisclaimerHTML:function(etDisclaimers){let floatingDisTemplate;if(typeof etDisclaimers.floating!=='string'){floatingDisTemplate=`
                    <div id="floating-disclaimer" class="floating-disclaimer">
                      <div class="full">${etDisclaimers.floating.textFull}</div>
                      <div class="mini">${etDisclaimers.floating.textMinified}</div>
                  </div>`;document.body.classList.add('floating2disclaimers');}else{floatingDisTemplate='<div id="floating-disclaimer" class="floating-disclaimer">'+etDisclaimers.floating+'</div>';document.body.classList.add('floating1disclaimer');}
const header_dis=document.getElementById('header_dis');if(!header_dis){return;}
if(etoro_disclaimers.alreadyInserted){return;}
const wrapperDiv=document.createElement('div');wrapperDiv.className='wrapper';wrapperDiv.innerHTML=floatingDisTemplate;header_dis.prepend(wrapperDiv);etoro_disclaimers.alreadyInserted=true;if(isUsaUkPage&&document.cookie.indexOf(disclaimerSettings.cookieHideDisclaimerName)===-1){document.body.classList.add(mini_mode_class);header_dis.classList.add('us-uk-disclaimer');}},observeDisclaimerResize:function(){if(typeof ResizeObserver!=='undefined'&&disclaimerObj){const resizeObserver=new ResizeObserver(function(){etoro_disclaimers.refreshDisStyle();});resizeObserver.observe(disclaimerObj);}else{window.addEventListener("orientationchange",etoro_disclaimers.refreshDisStyle);window.addEventListener("resize",etoro_disclaimers.refreshDisStyle);window.addEventListener("scroll",etoro_disclaimers.refreshDisStyle);}},applyGermanyRestrictions:function(){function hideOnCryptoPagesForGermany(){const cryptoBodyClass="page-template-template-crypto-pages";if(document.body.classList.contains(cryptoBodyClass)){document.body.classList.add('country-'+GERMANY);$('.crypto-exchange-page, .p1c2_list_2').remove();$('.co2, #co2','.p1c50_table').remove();$('.p1c5_item_3').remove();}}
function redirectAwayFromExchangePageForGermany(){const restrictedPage='crypto/exchange';const indexOf=window.location.pathname.indexOf(restrictedPage);if(indexOf!==-1){const rootIndex=window.location.pathname.indexOf('/exchange');const new_url=window.location.origin+window.location.pathname.substring(0,rootIndex+1)+window.location.search;$body.hide();window.location.replace(new_url);}}
redirectAwayFromExchangePageForGermany();hideOnCryptoPagesForGermany();},applySpainRestrictions:function(){if(document.body.classList.contains('stocks')){document.body.classList.add('show-specific-stocks-text');}},run:function(){etoro_disclaimers.applyRestrictions();window.isUsaUkPage=/^\/en-us\/options\/uk\//.test(location.pathname)||/^\/en-us\/news-and-analysis\/options-uk\//.test(location.pathname);const isUsaWebsite=/^\/en-us\//.test(location.pathname),showFloatingDisclaimer=(!isUsaWebsite||isUsaUkPage)&&etoroDisclaimers&&!etoroDisclaimers.hideDisclaimerInThisPage;if(showFloatingDisclaimer){document.addEventListener('definedCountryAndRegulation',etoro_disclaimers.renderFloatingDisclaimer);}
document.addEventListener('definedCountryAndRegulation',etoro_disclaimers.renderFooterDisclaimer);if(document.cookie.indexOf(disclaimerSettings.cookieHideDisclaimerName)>-1){document.body.classList.add("mini_mode");}
etoro_disclaimers.floatingDisclaimerUI();const floatingDisclaimerResizeObserver=new ResizeObserver(etoro_disclaimers.floatingDisclaimerUI);floatingDisclaimerResizeObserver.observe(document.body);etoro_disclaimers.handleMoreLessDisclaimerBtn();},applyRestrictions:function(){document.addEventListener('definedCountryAndRegulation',function(){if(eToroMarketingData.countryId===GERMANY){etoro_disclaimers.applyGermanyRestrictions();}
if(eToroMarketingData.countryId===SPAIN){etoro_disclaimers.applySpainRestrictions();}});},floatingDisclaimerUI:function(){const floating_disclaimer=document.getElementById('floating-disclaimer');if(!floating_disclaimer){return;}
const body_collapsible_disclaimer_class='collapsible-disclaimer';const should_be_mini=document.body.classList.contains(mini_mode_class);if(should_be_mini){document.body.classList.remove(mini_mode_class);}
const dis_height=floating_disclaimer.getBoundingClientRect().height;const lineHeight=parseInt(window.getComputedStyle(floating_disclaimer).lineHeight,10);if(should_be_mini){document.body.classList.add(mini_mode_class);}
if(document.body.classList.contains('floating2disclaimers')||dis_height>lineHeight*4-3){document.body.classList.add(body_collapsible_disclaimer_class);}else{document.body.classList.remove(body_collapsible_disclaimer_class);}},handleMoreLessDisclaimerBtn:function(){document.addEventListener('DOMContentLoaded',function(){const disExpandBtn=document.getElementById('dis-more-less');if(!disExpandBtn){return;}
disExpandBtn.addEventListener('click',function(){if(document.body.classList.contains(mini_mode_class)){document.body.classList.remove(mini_mode_class);window.deleteCookie(disclaimerSettings.cookieHideDisclaimerName);}else{document.body.classList.add(mini_mode_class);window.setCookie(disclaimerSettings.cookieHideDisclaimerName,'1',365);}});},false);}};etoro_disclaimers.run();})(jQuery);