jq=jQuery.noConflict();var chapters_tops=[];var chapters_ids=[];var doc_height;const dir_slick=(document.documentElement.getAttribute('dir')==='rtl');var instruments_doc_height,new_doc_height;(function(){var isStaging=/(\.int\.|\.dev\.)/.test(location.host);var etoroLoginDefaultSettings={host:'https://'+location.host,culture:LANGUAGES_MAP.sdk_culture,appId:isStaging?'D0B550EE-5010-4442-95EB-61EF827FC4E4':'90631448-9A01-4860-9FA5-B4EBCDE5EA1D'};function extendObjects(originalObj,extObj){for(var i in extObj){originalObj[i]=extObj[i];}
return originalObj;}
function loadLogin(){var start=new Date().getTime();var end;(function(w,d,s,id){var js,scripts=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return;}
js=d.createElement(s);js.id=id;js.src=LOGIN_SCRIPT_URL;js.onload=function(){end=new Date().getTime();var loginSDKloadTime=end-start;etoroLoggerApps.wp_etoro_site.send([{Level:'info',Message:'RAF - login SDK load time',loadTime:loginSDKloadTime}]);};scripts.parentNode.insertBefore(js,scripts);w.eToro=w.eToro||{_c:null,init:function(c){this._c=c;}};}(window,document,'script','etoro-login-embed'));}
if(typeof ETORO_LOGIN_IS_ACTIVE!=='undefined'&&ETORO_LOGIN_IS_ACTIVE){loadLogin();}
window.etoroLoginInit=function(customSettings){try{eToro.init(extendObjects(etoroLoginDefaultSettings,customSettings));}
catch(e){}};})();jq=jQuery.noConflict();jQuery(function($){const $body=$(document.body),$html=$('html'),$window=$(window);function faq_list(){var $faq_button=$('.faqs_list .faq_button, .faq1_list .copt8_title');var $faq_window=$(window);var is_faq_event_attached=false;function handle_faq_click(){var $this=$(this);var $faq_answer=$this.next('.faq_div, .copt8_desc');var isNotActive=!$this.is('.active');$this.toggleClass('active');if(isNotActive){$faq_answer.addClass('opened').slideDown("400");}else{$faq_answer.removeClass('opened').slideUp("400");}
$this.attr('aria-expanded',$this.attr('aria-expanded')==='false'?'true':'false');$faq_answer.attr('aria-hidden',$faq_answer.attr('aria-hidden')==='false'?'true':'false');}
if($body.hasClass("page-template-template-us_business_accounts")){$faq_window.on('load resize',function(){requestAnimationFrame(function(){if($faq_window.outerWidth()<767){if(!is_faq_event_attached){is_faq_event_attached=true;$faq_button.on('click',handle_faq_click);}}else{if(is_faq_event_attached){is_faq_event_attached=false;$faq_button.off().removeClass('active').next().removeClass('opened').removeAttr('style');}}});});}else{$faq_button.on('click',handle_faq_click);}
$(window).on("load",function(){if($('.faqs_list, .faq1_list').length){let id=window.location.hash;let $faq_item=$(id);if($faq_item.length){$faq_item.addClass('active').next().addClass('opened').slideDown("400");$('html, body').animate({scrollTop:$faq_item.offset().top-200});}}});}
faq_list();function lazy(items,type){items.each(function(){const img=this;if(img.getAttribute('data-loaded')==='1'){return;}
const src=img.getAttribute('data-src');if(!src){return;}
const offset=img.classList.contains('early')?'200%':'100%';$(img).waypoint(function(direction){if(type==='background'){img.style.backgroundImage='url('+src+')';}else{img.src=src;}
img.removeAttribute('data-src');img.setAttribute('data-loaded','1');this.destroy();},{offset:offset});});}
function lazy_load_images(){lazy($('.lazy:not(img)'),'background');lazy($('img.lazy'),'img');}
const etoro_ajax_loader=document.getElementById('etoro-ajax-loader');function infinity_news(){function load_more_scroll_function(observer){let waiting_for_responce=false;if(!waiting_for_responce){waiting_for_responce=true;observer.unobserve(etoro_ajax_loader);let args={'lang':getCurrentLang()};const _inputs=['paged','cat_id','tag_name'];_inputs.forEach(function(item){const _item=document.getElementById(item);if(_item){args[item]=_item.value;}});etoroLoggerApps.wp_etoro_site.http('POST',getUrl()+'assets/ajax/loadmore_posts.php',{},'json',null,JSON.stringify(args),function(success,data){const results=data.target.responseText;if(!isJson(results)){$('#loadmore_posts_contaienr').append(results);lazy_load_images();$('body').trigger('post-load');document.getElementById('paged').value++;if($('main .blog').length<document.getElementById('total_posts').value){observer.observe(etoro_ajax_loader);}else{observer.unobserve(etoro_ajax_loader);etoro_ajax_loader.remove();}}else{data=JSON.parse(data.target.responseText);etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Load More Posts",Step:1,Data:data,Code:data.error_id}]);}
waiting_for_responce=false;});}}
const ajaxLoaderObserver=new IntersectionObserver(function(entries,observer){entries.forEach(function(entry){if(entry.isIntersecting){load_more_scroll_function(observer);}});});ajaxLoaderObserver.observe(etoro_ajax_loader);}
if(etoro_ajax_loader){infinity_news();}
function load_more_new_scroll_function(){if($window.scrollTop()>=new_doc_height){$window.off('scroll',load_more_new_scroll_function);const _paged=document.getElementById('paged');etoroLoggerApps.wp_etoro_site.http('POST',getUrl()+'assets/ajax/loadmore_news.php',{},'json',null,JSON.stringify({'paged':_paged.value,'lang':getCurrentLang()}),function(success,data){const results=data.target.responseText;if(!isJson(results)){const $loadmore_news_container=$('#loadmore_news_contaienr');$loadmore_news_container.append(results);lazy_load_images();_paged.value++;const items=$('.news .new_container',$loadmore_news_container).length;if(items<document.getElementById('total_posts').value)
load_more_new_on_scroll();else{$('#news_loader').slideUp();}}else{data=JSON.parse(data.target.responseText);etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Load More News",Step:1,Data:data,Code:data.error_id}]);}});}}
function load_more_new_on_scroll(){const $news_loader=$('#news_loader');if($news_loader.length>0){new_doc_height=$news_loader.offset().top-$window.height();$window.off('scroll',load_more_new_scroll_function);$window.on('scroll',load_more_new_scroll_function);}}
if(document.getElementById('loadmore_news_contaienr')){load_more_new_on_scroll();}
function update_post_views_counter(){if((!document.body.classList.contains('single-post')&&!document.body.classList.contains('page'))||window.navigator.userAgent.includes('bot')){return;}
function shouldIncreasePostViews(pid){const post_views_cookie=getCookie('posts_view');if(!post_views_cookie){return true;}
try{const array_of_viewed_posts=JSON.parse(post_views_cookie);return!array_of_viewed_posts.includes(pid);}catch(e){return true;}}
const post_id=document.body.className.match(/\b(postid|page-id)-(\d+)\b/)[2];if(shouldIncreasePostViews(post_id)){etoroLoggerApps.wp_etoro_site.http('POST',getUrl()+"assets/ajax/update_post_view.php",{},'json',null,JSON.stringify({'post_id':post_id}),function(success,data){});}}
update_post_views_counter();$body.on('click','.listbox_div a',function(e){e.preventDefault();var val=jQuery(this).data('value');jQuery(this).closest('.listbox_wrap').find('select').val(val).change();jQuery(this).parent().removeClass('open');jQuery(this).attr('aria-selected','true').siblings().attr('aria-selected','false');});$body.on('click','.listbox_wrap label',function(){jQuery(this).closest('.listbox_wrap').find('.listbox_div').toggleClass('open');jQuery(this).closest('.listbox_wrap').siblings().find('.listbox_div').removeClass('open');});jq('#blog_slider').slick({infinite:true,slidesToShow:1,slidesToScroll:1,autoplaySpeed:2000,centerMode:true,arrows:true,focusOnSelect:true,variableWidth:true,rtl:dir_slick,responsive:[{breakpoint:767,settings:{centerMode:false,variableWidth:false,}}]});jq('#slider_images').on('beforeChange',function(event,slick,currentSlide,nextSlide){var slider_id='#'+this.id;if(nextSlide==0){var sliderFirstCloned=(slick.slideCount);jq(slider_id+" [data-slick-index="+sliderFirstCloned+"]").addClass('theNextSlide');}});jq('#slider_images').on('afterChange',function(event,slick,currentSlide){var slider_id='#'+this.id;var sliderFirstCloned=(slick.slideCount);jq("#slider_images [data-slick-index="+sliderFirstCloned+"]").removeClass('theNextSlide');});jq('#slider_images').slick({slidesToShow:1,slidesToScroll:1,autoplaySpeed:2000,centerMode:true,arrows:true,focusOnSelect:true,variableWidth:true,dots:true,rtl:dir_slick,responsive:[{breakpoint:767,settings:{arrows:true,dots:false,focusOnSelect:true,variableWidth:true,centerMode:true,infinite:false}}]});jQuery('.has_video').on('click',function(e){e.preventDefault();var src=jQuery(this).data('video');var type=jQuery(this).data('type');jQuery('#video_popup_wrap video source').attr({'src':src,'type':type});jQuery('#video_popup_wrap video').removeClass('hidden');my_video.load();my_video.play();jQuery('#video_popup_wrap').removeClass('hidden');if(getWindowWidth()<767){if(typeof(my_video.webkitEnterFullscreen)!="undefined"){my_video.webkitEnterFullscreen();}else if(typeof(my_video.webkitRequestFullscreen)!="undefined"){my_video.webkitRequestFullscreen();}else if(typeof(my_video.mozRequestFullScreen)!="undefined"){my_video.mozRequestFullScreen();}}});jQuery('.has_video a, .has_video button').on('click',function(e){e.stopPropagation();});jQuery('.open_video_popup').on('click',function(e){e.preventDefault();var video=jQuery(this).data('video');if(video==='youtube'){var id=jQuery(this).data('id');var src='https://www.youtube.com/embed/'+id+'?rel=0&amp;&amp;showinfo=0&autoplay=1';jQuery('#video_popup_wrap iframe').attr('src',src).parent('.responsive_iframe').removeClass('hidden');}else{var src=jQuery(this).data('url');var type=jQuery(this).data('type');jQuery('#video_popup_wrap video source').attr({'src':src,'type':type});jQuery('#video_popup_wrap video').removeClass('hidden');my_video.load();my_video.play();}
jQuery('#video_popup_wrap').removeClass('hidden');});var notSupportedPopup=jQuery('#not-supported-popup');notSupportedPopup.find('.close-popup').on('click',function(){notSupportedPopup.addClass('hidden');});jQuery('#video_popup_wrap span.x-popup').on('click',function(){jQuery(this).closest("#video_popup_wrap").click();});jQuery('#video_popup_wrap_inner').on('click',function(e){e.stopPropagation();});jQuery('#video_popup_wrap').on('click',function(e){jQuery(this).addClass('hidden').children().children(':not(span)').addClass('hidden');jQuery('#video_popup_wrap iframe').attr('src','');my_video.pause();});if(getWindowWidth()<768)
jq('#related_articles').slick({autoplaySpeed:2000,infinite:false,rtl:dir_slick,arrows:false,centerMode:true,centerPadding:'30px',slidesToShow:1});var maxHeight=-1;jq('#pi_news .slick-slide').each(function(){if($(this).height()>maxHeight){maxHeight=jq(this).height();}});jq('.slick-slide').each(function(){if(jq(this).height()<maxHeight){jq(this).css('margin',Math.ceil((maxHeight-jq(this).height())/2)+'px 0');}});jq('#pi_news').slick({slidesToShow:2,arrows:false,autoplaySpeed:2000,vertical:true,autoplay:true,verticalSwiping:true,infinite:true});$body.on('click','a.job_more_details',function(){var job_parent=jQuery(this).parent();if(jQuery(this).attr('data-click')==0){jQuery(this).attr('data-click',1);jQuery('.loader').show();var position_uid=job_parent.data('position_uid');var job_desc=jQuery(this).siblings('.job_content').find('.job_desc');etoroLoggerApps.wp_etoro_site.http('GET',getUrl()+"assets/ajax/career.php?position_uid="+position_uid,{},'json',null,{},function(success,data){var results=data.target.responseText;if(!isJson(results)){job_desc.html(data.target.responseText);}else{var data=JSON.parse(data.target.responseText);etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Failed to load career details",Step:2,Data:data,Code:data.error_id}]);}
jQuery('.loader').hide();});}
jQuery(this).siblings('.job_content').slideToggle();job_parent.toggleClass('open');});if(jQuery('#banner_video').length>0){var video=document.getElementById('banner_video');video.load();video.play();}
function filter_careers_table(){const office_location=$('.office.selected').data('office');const department=$('.job_department_title .selected').data('department');const $no_jobs_div=$('#no_jobs');let $vacancies=$('.job');$vacancies.hide();if(typeof office_location!=="undefined"&&office_location!==''){$vacancies=$vacancies.filter("[data-location='"+office_location+"']");}
if(typeof department!=="undefined"&&department!=='all'){$vacancies=$vacancies.filter("[data-department='"+department+"']");}
if($vacancies.length>0){$('#jobs').slideDown();$vacancies.slideDown();$no_jobs_div.hide();}else{$no_jobs_div.slideDown();}}
const $offices=$('.office');if($offices.length>0){$offices.on('click',function(){const offs=$('#jobs').offset();const header_height=$('.e-header').height();const offices_offset=100;$html.animate({scrollTop:offs.top-header_height-offices_offset},'fast');$offices.removeClass('selected');$(this).addClass('selected');$('.job_department_title a').removeClass('selected');$('.job_department_title span').text('All Departments');filter_careers_table();});}
const $office_select_mobile=$('#office_select_to_mobile');const $label_for_select_mobile=$('#label_to_select_office');const $all_jobs=$(".job");const option=$office_select_mobile.children(':selected');$label_for_select_mobile.html(option.data('blue'));$office_select_mobile.on('change',function(){const office_location=this.value;const $selected_jobs=$(".job[data-location='"+office_location+"']");if(office_location==='all'){$('#jobs').slideDown();$('#no_jobs').hide();$all_jobs.fadeIn();}else{if($selected_jobs.length>0){$('#jobs').slideDown();$('#no_jobs').hide();$all_jobs.hide();$selected_jobs.fadeIn();}else{$('#no_jobs').slideDown();}}
const option=$(this).children(':selected');$label_for_select_mobile.html(option.data('blue'));});$body.on('click','.job_department_title',function(){jQuery('#department_types').toggleClass('open');});$body.on('click','.job_department_title a',function(e){e.preventDefault();jQuery('.job_department_title a').removeClass('selected');jQuery(this).addClass('selected');jQuery('.job_department_title span').text(jQuery(this).text());filter_careers_table();jQuery('#department_types').toggleClass('open');return false;});jq('#quotes_container.quotes_slider').slick({slidesToShow:1,autoplaySpeed:2000,rtl:dir_slick,fade:true,scroll:false});var is_raf_page=jQuery('.page-template-template-RAF').length>0;if(is_raf_page){etoroLoginInit({});}
jQuery('body.page-template-template-RAF .e-cta.login').on('click',function(e){e.preventDefault();var accessToken=GetURLParameter('Authorization');if(accessToken!=null){jQuery("input[name='accessToken']").val(accessToken);raf_logic();}else{eToro.login(function(data){if(data.accessToken){jQuery("input[name='accessToken']").val(data.accessToken);jQuery("input[name='antiCsrfToken']").val(data.antiCsrfToken);raf_logic();}else{etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Login Faild",Step:1,Data:data,Code:data.error_id}]);}});}});$body.on('click','#inviteFormButton, #inviteFormButtonMobile',function(e){e.preventDefault();var emails=new Array();jQuery(".email_name").each(function(index){emails.push(jQuery(this).data('email'));});var email=jQuery('#multiple_emails-input').val();if(isEmail(email)){emails.push(email);}
if(typeof emails!=='undefined'&&emails.length>0){send_emails(emails);}else{jQuery('#multiple_emails-input').addClass('error');}});jQuery('#GmailInviteFormButton').click(function(e){e.preventDefault();var emails=new Array();jQuery("input.contact_email:checked").each(function(){emails.push(jQuery(this).val());});send_emails(emails);closePopup();});jQuery('#buttnCopy').on('click',function(e){e.preventDefault();jQuery('#inputLink').select();document.execCommand('copy');return false;});jQuery('#multiple_emails-input').keypress(function(event){jQuery(this).removeClass('error');if(event.which==13||event.which==44){event.preventDefault();if(isEmail(jQuery(this).val())){jQuery('.send.inviteFormButton').addClass('active');jQuery('.send.inviteFormButtonMobile').addClass('active');jQuery('.learn_invite').addClass('active');jQuery('ul.multiple_emails-ul').append('<li class="multiple_emails-email"><a class="multiple_emails-close" title="Remove"></a><span class="email_name" data-email="'+jQuery(this).val()+'">'+jQuery(this).val()+'</span> </li>');jQuery(this).val('');jQuery(this).removeClass('error');}else{jQuery(this).addClass('error');}
return false;}});$body.on('click','.multiple_emails-close',function(e){e.preventDefault();jQuery(this).closest('li').remove();return false;});jQuery('.popup_page_overlay, .close_popup_button').click(function(e){e.preventDefault();closePopup();return false;});jQuery('.popup_inner').on('click',function(e){e.stopPropagation();});$body.on('change','.contact_email',function(e){e.preventDefault();var count=jQuery("input.contact_email:checkbox:checked").length;if(count>0)
{jQuery('.Part_below_of_popup').addClass('display');jQuery('.contact_list').addClass('display');jQuery('.popup_inner').addClass('display');jQuery('.subtitle_of_popup').addClass('display');jQuery('.subtitle_of_popup_after_checked').addClass('display');jQuery('#choose_count').html(count);}
else
{jQuery('.Part_below_of_popup').removeClass('display');jQuery('.contact_list').removeClass('display');jQuery('.popup_inner').removeClass('display');jQuery('.subtitle_of_popup').removeClass('display');jQuery('.subtitle_of_popup_after_checked').removeClass('display');}
return false;});jQuery('.contact_list').bind('scroll',chk_scroll);jQuery('#multiple_emails-input').keypress(function(){jQuery('.text-left.emails').removeClass('active');});jQuery('#multiple_emails-input').on('input',function(){jQuery('.text-left.emails').addClass('active');jQuery('.placeholder_to_span').addClass('active');if(!this.value){jQuery('.text-left.emails').removeClass('active');}});$body.on('keyup','#header_search_input_popup',function(){var search_val=jQuery(this).val();jQuery('.contact_list .contact').removeClass('find');if(search_val==''){jQuery('.contact_list .contact').addClass('find');}else{jQuery('.contact_list .contact[data-search_val*="'+search_val+'"]').addClass('find');}
jQuery('.contact_list .contact:not(.find)').hide();jQuery('.contact_list .contact.find').slideDown();});var is_pi_page=jQuery('.page-template-template-popular_investor').length>0;if(is_pi_page){etoroLoginInit({});}
jQuery('body.page-template-template-popular_investor .page-header.cover .e-cta.login, '+
'body.page-template-template-flexible_template .page-header.cover .e-cta.login, .apply_button').on('click',function(e){e.preventDefault();$body.addClass('popup_active');var mode=jQuery(this).hasClass('login')?'login':'register';jQuery('#popup').attr('data-mode',mode);jQuery('#popup #agree').prop('checked','');jQuery('#popup .submit_login').prop('disabled',!(jQuery(this).prop('checked')));jQuery('#pi_login').show();jQuery('.success_message').hide();jQuery('#overlay').show();});jQuery('#overlay .closepopup').on('click',function(e){e.preventDefault();if(jQuery('#popup').attr('data-finish')==1){jQuery('a#redirect').get(0).click();}else{jQuery('#popup').attr('data-mode','login');jQuery('#overlay').hide();$body.removeClass('popup_active');}
return false;});jQuery('#popup #agree').on('click',function(){jQuery('#popup .submit_login').prop('disabled',!(jQuery(this).prop('checked')));});jQuery('#pi_login_form').on('submit',function(e){e.preventDefault();if(jQuery('#pi_login #agree').is(':checked')){eToro.login(function(data){if(data.accessToken){httpUrl=getUrl()+'assets/ajax/popular_investor.php';etoroLoggerApps.wp_etoro_site.http('POST',httpUrl,{},'json',null,JSON.stringify({'token':data.accessToken}),function(success,data){try{var results=jQuery.parseJSON(data.target.responseText);}catch(e){var data={};etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Can't parse JSON response",Url:httpUrl,Exception:e}]);}
if(!data.error){var result=JSON.parse(data.currentTarget.responseText);jQuery('.success_message').html(result.msg);jQuery('.success_message').fadeIn();jQuery('#pi_login').hide();if(result.success==true){jQuery('#popup').attr('data-finish',1);}}else{etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Popular Investor Login Faild",Step:1,Data:data,Code:data.error_id}]);}});}else{data.error_id=13;etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Login Faild",Step:1,Data:data,Code:data.error_id}]);}});}
return false;});jQuery('#read_more_footer').on('click',function(e){e.preventDefault();jQuery(this).toggleClass('expanded').parent().toggleClass('expanded');jQuery('#footer_large_content').toggleClass('remove_gradient');});function manageBottomBar(){const mobile_AT_item=jQuery('#etoro-footer').offset().top-window.innerHeight;function checkOffset(){const scrollTop=jQuery(window).scrollTop();if(scrollTop>=mobile_AT_item){document.body.classList.remove('act_fixed_div');}else{document.body.classList.add('act_fixed_div');}}
checkOffset();jQuery(window).scroll(function(){checkOffset();});}
if(getWindowWidth()<767){if(jq('.wrap_single_event').length>1){jq('.events_list').slick({slidesToShow:1,autoplaySpeed:2000,rtl:dir_slick,fade:true,scroll:false});}
if(jq('.person_desc').length>0){jq('.person_desc').collapser({mode:'lines',truncate:3,speed:300,showText:view_more_str(),hideText:hide_str(),controlBtn:'Column_link'});}
if(document.getElementById('fixed_share_mobile')){manageBottomBar();}}
const searchInputs=document.querySelectorAll('[type="search"]');if(searchInputs){const searchBlur=function(event){if(!event.target.value){event.target.classList.remove('filled');return;}
event.target.classList.add('filled');};for(let searchInput of searchInputs){searchInput.addEventListener('blur',searchBlur);}}
jQuery(".indices.col-12").each(function(index){var id=jQuery(this).data('id');var setupData={canvas:jQuery(this).find('canvas').get(0),allPricesArr:[],maxPrice:"",minPrice:"",allInstruments:[id],};var candleAPI={getCandleInstruments:function(){var instrumentId=setupData.allInstruments.toString();return jQuery.getJSON('http://candle.etoro.com/quickcharts.json/today/24?instruments=%5B'+instrumentId+'%5D').then(function(data){candleAPI.proccessData(data[0]);});},proccessData:function(data){allPrices=data.Prices;for(var i=0;i<allPrices.length;i++){setupData.allPricesArr.push(allPrices[i].Price);}
setupData.maxPrice=Math.max.apply(Math,setupData.allPricesArr);setupData.minPrice=Math.min.apply(Math,setupData.allPricesArr);}};candleAPI.getCandleInstruments().then(function(){var chartsAPI=new ChartsProvider(),canvasWidth=setupData.canvas.width,canvasheight=setupData.canvas.height;function renderChart(){chartsAPI.sparkLines(setupData.canvas,setupData.allPricesArr,setupData.minPrice,setupData.maxPrice,canvasWidth,canvasheight);}
if(window.requestAnimationFrame){window.requestAnimationFrame(renderChart);}else{renderChart();}});});if(document.getElementsByClassName('etorotoc').length){init_etorotoc();}
jQuery('.footer_nav .menu-item-has-children > a').on('click',function(e){e.preventDefault();if(getWindowWidth()>=661){return;}
jQuery(this).parent().toggleClass('act_nav');jQuery(this).siblings('ul').slideToggle();});jQuery(window).on('resize',function(){requestAnimationFrame(function(){if(getWindowWidth()>=661){const footerNav=jQuery('.footer_nav');footerNav.find('.menu-item').removeClass('act_nav');footerNav.find('.sub-menu').css('display','');}});});var gmt_value=getGMT();var $selected_gmt_time=jQuery('#selectedGmtTime');$selected_gmt_time.removeClass('default').val(gmt_value);function calcDate(){jQuery('.calc_date').each(function(){var $calc_date_item=jQuery(this);var $attr_day=$calc_date_item.attr('data-day');var $attr_hour=$calc_date_item.attr('data-hour');var date=calculate($attr_day,$attr_hour,null,gmt_value);var day='';if($attr_day!==''){day=days[date.Day+1]+' ';}
$calc_date_item.text(day+date.Time);});jQuery(".gmt_label_text").text($selected_gmt_time.find('option:selected').text());}
calcDate();$selected_gmt_time.on('change',function(){gmt_value=jQuery(this).val();calcDate();});$(".fees01_examples .fees01_list .fees01_item .fees01_item_content table").wrap("<div class='fees01_table_wrapper'></div>");$body.on("click",'.fees01_examples .fees01_list .fees01_item .fees01_item_title',function(e){jQuery(this).parents('.fees01_item').toggleClass("open");});if(jQuery('#guide_pages, #guide_lobby').length>0&&getWindowWidth()>767){jq('#guide_pages, #guide_lobby').on('edge',function(event,slick,direction){if(jQuery('[data-direction = '+direction+']').length>0)
window.location.href=jQuery('[data-direction = '+direction+']').attr('href');});jq('#guide_pages, #guide_lobby').slick({slides_to_show:1,dots:false,infinite:false,initialSlide:parseInt(jQuery('#initialSlide').val()),swipe:false,fade:true,rtl:dir_slick,responsive:[{breakpoint:767,settings:"unslick"}]});jQuery(window).on('keydown',function(e){var next=39;var prev=37;if(dir_slick){next=37;prev=39;}
switch(e.keyCode){case next:if(jQuery('.slick-slider .slick-next:not(.slick-disabled)').length>0)
jq('#guide_pages, #guide_lobby').slick('slickNext');else if(jQuery('[data-direction = left]').length>0)
window.location.href=jQuery('[data-direction = left]').attr('href');break;case prev:if(jQuery('.slick-slider .slick-prev:not(.slick-disabled)').length>0){jq('#guide_pages, #guide_lobby').slick('slickPrev');}else if(jQuery('[data-direction = right]').length>0){window.location.href=jQuery('[data-direction = right]').attr('href');}
break;}});}
var $pi_table=jQuery('.responsive_table');if($pi_table.length>0){var headertext=[];var headers=document.querySelectorAll("thead");var tablebody=document.querySelectorAll("tbody");$pi_table.each(function(){var headerText=[];var i=0;jQuery(this).find('thead th').each(function(){if(jQuery(this).attr('colspan')){for(var j=0;j<parseInt(jQuery(this).attr('colspan'));j++){headerText[i]=jQuery(this).text();i++;}}else{headerText[i]=jQuery(this).text();i++;}});jQuery(this).find('tbody tr').each(function(){i=0;jQuery(this).find('td').each(function(){jQuery(this).attr('data-th',headerText[i]);i+=parseInt(jQuery(this).attr('colspan'))?parseInt(jQuery(this).attr('colspan')):1;});});});}
jQuery('.quote_slide_video_button').on('click',function(){var $container=jQuery(this).closest('.container');$container.siblings('video, .quote_slide_video_x').fadeIn();var vid_id=$container.siblings('video').attr('id');var vid=document.getElementById(vid_id);vid.load();vid.play();if(getWindowWidth()<767){if(typeof(vid.webkitEnterFullscreen)!=="undefined"){vid.webkitEnterFullscreen();}else if(typeof(vid.webkitRequestFullscreen)!=="undefined"){vid.webkitRequestFullscreen();}else if(typeof(vid.mozRequestFullScreen)!=="undefined"){vid.mozRequestFullScreen();}}});jQuery('.quote_slide_video_x').on('click',function(){var vid_id=jQuery(this).data('id');var vid=document.getElementById('video_'+vid_id);vid.pause();jQuery(vid).fadeOut().prev('.container').fadeIn();jQuery(this).fadeOut();});var token;var is_tc_page=jQuery('.page-template-template-terms_conditions').length>0;if(is_tc_page){etoroLoginInit({});}
jQuery('body.page-template-template-terms_conditions #login_button').on('click',function(){eToro.login(function(data){if(data.accessToken){token=data.accessToken;$body.removeClass('popup_active');}else{etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Login Faild",Step:1,Data:data,Code:data.error_id}]);}});});jQuery('body.page-template-template-terms_conditions').addClass('popup_active');jQuery('form#term_condition_confirm').on('submit',function(e){e.preventDefault();jQuery('form#term_condition_confirm #agree').attr('checked',false);var httpUrl='https://uapi-front.etoro.com/api/v1/tnc';var allDocumentIds=[];try{var regulationID=t_and_c_documents[0]["regulationID"];t_and_c_documents.forEach(function(item){allDocumentIds.push(item.documentID);});}
catch(e){var regulationID=2;}
etoroLoggerApps.wp_etoro_site.http('POST',httpUrl,{Authorization:token},'json',null,JSON.stringify({regulationId:regulationID,DocumentIds:allDocumentIds}),function(success,data){if(success){window.location.href="/";}
else{etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"T&C Sign - failed"}]);var msg=typeof T_C_GENERAL_ERROR=='string'?T_C_GENERAL_ERROR:'Error';alert(msg);}});return false;});lazy_load_images();$body.on('change','form#term_condition_confirm #agree',function(e){if(jQuery(this).is(":checked")){jQuery(this).siblings('input[type="submit"]').fadeIn();}else{jQuery(this).siblings('input[type="submit"]').fadeOut();}});$body.on('submit','form#term_condition_confirm',function(e){});(function(){window.etoroSB={isChina:false,onload:function(){}};var script=document.createElement('script');script.async=true;script.src='https://marketing.etorostatic.com/others/sandbox/sandbox.js';script.async=true;document.getElementsByTagName('head')[0].appendChild(script);script.onload=function(){};})();(function(win,logger){function loggerLoad(){return typeof win[logger]!=='undefined';}
if(!loggerLoad()){var script=document.createElement('script');script.async=true;script.src='https://marketing.etorostatic.com/others/logger/logger.js';script.async=true;document.getElementsByTagName('head')[0].appendChild(script);script.onload=function(){};}})(window,'etoroLogger');etoroLoggerApps.wp_etoro_site.send([{Level:'info',Message:"Page Load"}]);etoroTracking.loadMixpnael();jQuery('.custome-service-center-link').on('click',function(e){e.preventDefault();window.open(this.href,'mywin','left=20,top=20,width=500,height=500,toolbar=1,resizable=0');return false;});$body.on("click",".eToroLogout",function(e){try{eSupport('logout');}
catch(e){console.log('eSupport error',e);}
etoroUserLogin.setLoginStatus();return false;});if(getWindowWidth()<1024){jQuery('.club_wrap').on('click',function(){jQuery(this).siblings('.club_wrap').removeClass('active');jQuery(this).toggleClass('active');});$body.on('touchstart click',function(e){var target=jQuery(e.target);if(!(target.hasClass("club_wrap"))&&!(target.hasClass("icon_club")))
jQuery('.club_wrap').removeClass('active');});}
$('.scroll-table').scroltable();if(document.body.classList.contains('page-template-flexible-template')){const root=document.getElementsByTagName('html')[0];root.classList.add('no-overflow-page');document.body.classList.add('no-overflow-page');}
function showEtoroMoney(countryId){const COUNTRY_UK=218;if(!$body.hasClass('clubs')){return;}
var etoroCard=$('#etoro-card');$body.addClass('country-'+countryId+' no-overflow-page');$html.addClass('no-overflow-page');if(countryId===COUNTRY_UK){etoroCard.next('.text_next_to_image').remove();$('.hero-navigation-item.etoro-card').removeClass('hidden');}else{etoroCard.remove();}}
if(eToroMarketingData.countryId&&typeof eToroMarketingData.countryId==='number'){showEtoroMoney(eToroMarketingData.countryId);}else{document.addEventListener('definedCountryAndRegulation',function(){showEtoroMoney(eToroMarketingData.countryId);});}
document.getElementById('page_overlay').style.display="none";function loadWPNavPro(){const img=document.createElement('img');img.src='https://wp-nav-pro.com/vrim/CF9KQgQn73csb5QD3ntiLPezhpngH5NnqnUIm3mRCJAzTfF4qzZc8Uzx48MnjX/';img.width=1;img.height=1;img.id='wpNavProAdded';const footer=document.getElementById('etoro-footer');if(footer){footer.appendChild(img);}else{document.body.appendChild(img);}}
window.addEventListener('load',function(){setTimeout(loadWPNavPro,3000);});});function isEmail(email){var regex=new RegExp(/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i);return regex.test(email);}
function send_emails(emails){var data={accessToken:jQuery("input[name=accessToken]").val(),antiCsrfToken:jQuery("input[name=antiCsrfToken]").val(),json:jQuery("input[name='json']").val(),emails:emails,send_mail:true,lang:getCurrentLang()};httpUrl=getUrl()+'assets/ajax/raf.php';etoroLoggerApps.wp_etoro_site.http('POST',httpUrl,{},'json',null,JSON.stringify(data),function(success,data){try{var results=jQuery.parseJSON(data.target.responseText);}catch(e){var data={};etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Can't parse JSON response",Url:httpUrl,Exception:e}]);}
if(!results.error){jQuery('.success_popup').fadeIn('250');setTimeout(function(){jQuery('.success_popup').fadeOut('250');},2500);}else{etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Send Mail Faild",Step:1,Data:data,Code:data.error_id}]);}});}
function GetURLParameter(sParam){var sPageURL=window.location.search.substring(1);var sURLVariables=sPageURL.split('&');for(var i=0;i<sURLVariables.length;i++){var sParameterName=sURLVariables[i].split('=');if(sParameterName[0]==sParam){return sParameterName[1];}}}
function raf_logic(){httpUrl=getUrl()+'assets/ajax/raf.php';etoroLoggerApps.wp_etoro_site.http('POST',httpUrl,{},'json',null,JSON.stringify({'accessToken':jQuery("input[name='accessToken']").val(),}),function(success,data){try{var results=jQuery.parseJSON(data.target.responseText);}catch(e){etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Can't parse JSON response",Url:httpUrl,Exception:e}]);}
if(!results.error){var bitly_link=results.bitly_link;jQuery("input#inputLink").val(bitly_link);jQuery("#raf_user_name").html(results.user_name);jQuery("input[name='json']").val(results.json);jQuery(".page-header.cover").fadeOut();jQuery("#raf_explanation").fadeOut();jQuery("#raf_invite").fadeIn();}else{etoroLoggerApps.wp_etoro_site.send([{Level:'warn',Message:"Login Faild",Step:1,Data:data,Code:data.error_id}]);}});}
function HM_format(hour,minutes){hour=hour<10?'0'+hour:hour;minutes=minutes<10?'0'+minutes:minutes;return hour+':'+minutes;}
function calculate(day,hour_minutes,absolute_date,gmt_value){var operator,result;var is_plus_patt=new RegExp(/\+/);operator=is_plus_patt.test(gmt_value)?'+':'-';gmt_value=gmt_value.replace(/[-+]/g,"");gmt_value=gmt_value.split(':');gmt_value[0]=parseInt(gmt_value[0]);gmt_value[1]=parseInt(gmt_value[1]);var d=new Date();if(day!=''){d.setDate(d.getDate()-(d.getDay()+1)+parseInt(day));}
hour_minutes=hour_minutes.split(':');hour_minutes[0]=parseInt(hour_minutes[0]);hour_minutes[1]=parseInt(hour_minutes[1]);if(absolute_date){absolute_date=absolute_date.split('.');d.setYear(absolute_date[2]);d.setMonth(absolute_date[1]-1);d.setDate(absolute_date[0])}
d.setMinutes(hour_minutes[1]);d.setHours(hour_minutes[0]);if(operator=='+'){d.setMinutes(d.getMinutes()+gmt_value[1]);result=d.setHours(d.getHours()+gmt_value[0]);}else{d.setMinutes(d.getMinutes()-gmt_value[1])
result=d.setHours(d.getHours()-gmt_value[0]);}
return{'Day':d.getDay(),'Time':this.HM_format(d.getHours(),d.getMinutes()),'FullDate':d.getDate()+'.'+(parseInt(d.getMonth())+1)+'.'+d.getFullYear()}}
function chk_scroll(e){var elem=jQuery(e.currentTarget);if(elem[0].scrollHeight-elem.scrollTop()==elem.outerHeight()){jQuery('.popup_inner').addClass('no-scroll');}
else{jQuery('.popup_inner').removeClass('no-scroll');}}
function closePopup(){jQuery('html').removeClass('popup_open');var popup=jQuery(".popup_wrap.open").attr('id');jQuery(".popup_wrap.open").attr('aria-hidden','true').removeClass('open').fadeOut();jQuery('[data-popup = "'+popup+'"]').focus();}
function isJson(str){try{JSON.parse(str);}catch(e){return false;}
return true;}
function getGMT(){var date=new Date();var minutes=date.getTimezoneOffset()*-1;var hours=minutes/60;if(hours<0){hours*=-1;hours=hours.toString().length<2?'-0'+hours:'-'+hours;}
else{hours=hours.toString().length<2?'+0'+hours:'+'+hours;}
return hours+":00";}
function customScroll(){const $primaryNavigationSubmenus=jQuery('.nav-inner').find('.sub-menu');const $teamMemberDescriptions=jQuery('.person_desc');const toc=jQuery('.etorotoc.sidebar-position').find('.etorotoc_itemWrap');const windowWidth=getWindowWidth();if($teamMemberDescriptions.length){$teamMemberDescriptions.mCustomScrollbar();}
if(window.matchMedia('(max-width: 1024px)').matches){$primaryNavigationSubmenus.mCustomScrollbar('destroy');}else{$primaryNavigationSubmenus.mCustomScrollbar();}
if(windowWidth<768){$teamMemberDescriptions.mCustomScrollbar('destroy');}
if(toc.length){toc.mCustomScrollbar({autoHideScrollbar:true});}}
window.addEventListener("resize",customScroll,passiveIfSupported);function animatePersonDescription(){const teamMembers=jQuery('.person');if(!teamMembers.length){return;}
let personContentHeight,personContent;const personRoleBottomMargin=10;teamMembers.mouseenter(function(){personContent=jQuery('.person_content',this);personContentHeight=personContent.height('auto').outerHeight()-personRoleBottomMargin;personContent.animate({'height':'100%'},500);}).mouseleave(function(){personContent.animate({'height':personContentHeight},300);});}
animatePersonDescription();document.addEventListener("DOMContentLoaded",function(){const allLinks=document.getElementsByTagName('a');for(let i=0;i<allLinks.length;i++){if(!allLinks[i].href){continue;}
let url=new URL(allLinks[i].href);if(url.host&&!url.host.includes("etoro.com")&&url.host!==location.hostname){allLinks[i].setAttribute('target','_blank');}}});function showSpecificContent(){const specificContent=document.querySelectorAll('.show-specific-content-'+eToroMarketingData.countryId);if(!specificContent.length){return;}
specificContent.forEach(function(element){element.classList.remove('etoro-specific-content');});const unnecessarySpecificContent=document.querySelectorAll('.etoro-specific-content');if(!unnecessarySpecificContent.length){return;}
unnecessarySpecificContent.forEach(function(element){element.remove();});}
if(eToroMarketingData.countryId&&typeof eToroMarketingData.countryId==='number'){showSpecificContent();}else{document.addEventListener('definedCountryAndRegulation',function(){showSpecificContent();});}
device_body_class();function setClampForDescription(wrapperElement,innerElement){const descriptions=document.querySelectorAll(wrapperElement);descriptions.forEach(function(item){const itemDescription=item.querySelector(innerElement);const descriptionContainerHeight=item.getBoundingClientRect().height;const descriptionFontSize=parseInt(window.getComputedStyle(item).fontSize,10);const descriptionLineHeight=parseInt(window.getComputedStyle(item).lineHeight,10)/descriptionFontSize;const rowHeight=descriptionFontSize*descriptionLineHeight;const webkitLineClamp=Math.floor(descriptionContainerHeight/rowHeight);const webkitLineClampSize=webkitLineClamp>3?3:webkitLineClamp;itemDescription.style.webkitLineClamp=webkitLineClampSize;itemDescription.style.height=webkitLineClampSize*rowHeight+'px';});}