"use strict";(function(){if(typeof window.CustomEvent==="function"){return false;}
function CustomEvent(event,params){params=params||{bubbles:false,cancelable:false,detail:null};let evt=document.createEvent('CustomEvent');evt.initCustomEvent(event,params.bubbles,params.cancelable,params.detail);return evt;}
window.CustomEvent=CustomEvent;})();window.eToroMarketingData={};let EToroRegulationsService=function(eToroWP,etoroUserLogin,loggers){let eveName='definedCountryAndRegulation';this.config={eventName:eveName,ev:new CustomEvent(eveName),cookieVisitorRegulationName:eToroWP.cookieVisitorRegulationName,cookieUserDesignatedRegulationName:eToroWP.cookieUserDesignatedRegulationName,cookieVisitorCountryName:eToroWP.cookieVisitorCountryName,cookieUserCountryName:eToroWP.cookieUserCountryName};this.etoroUserLogin=etoroUserLogin;this.loggers=loggers;this.getRegulationAndCountry();};EToroRegulationsService.prototype.run=function(){document.dispatchEvent(this.config.ev);};EToroRegulationsService.prototype.getCookie=function(name){let matches=document.cookie.match(new RegExp("(?:^|; )"+name.replace(/([.$?*|{}()\[\]\\\/+^])/g,'\\$1')+"=([^;]*)"));return matches?decodeURIComponent(matches[1]):undefined;};EToroRegulationsService.prototype.setCookie=function(c_name,value,exdays){let exdate=new Date();exdate.setDate(exdate.getDate()+exdays);let c_value=escape(value)+
((exdays==null)?'':'; expires='+exdate.toUTCString());document.cookie=c_name+'='+c_value+';path=/';};EToroRegulationsService.prototype.setUserMarketingData=function(){let _this=this;if(_this.inProgress){return;}
_this.inProgress=true;let stsData=_this.etoroUserLogin.getLoginData();if(!stsData||!stsData.accessToken||!localStorage.userInfo){return;}
let u=JSON.parse(localStorage.userInfo);if(typeof u!=='object'||!u.cid){return;}
const httpUrl='https://www.etoro.com/api/logininfo/v1.1/logindata?conditionIncludeDisplayableInstruments=false&conditionIncludeMarkets=false&conditionIncludeMetadata=false&conditionIncludeMirrorValidation=false';const logger=_this.loggers['wp_etoro_site'];logger.http('GET',httpUrl,{authorization:stsData.accessToken,accounttype:'Real',applicationIdentifier:'marketingSites',applicationversion:'1'},'',null,'',function(success,xhr_data){if(!success){logger.send([{Level:'warn',Url:httpUrl,Message:"failed to get logindata",Exception:xhr_data}]);return;}
try{let data=JSON.parse(xhr_data.target.responseText);let designatedRegulationId=data.AggregatedResult.ApiResponses.CurrentUserData.Content.users[0].designatedRegulationId;let countryId=data.AggregatedResult.ApiResponses.CurrentUserData.Content.users[0].country;if(!designatedRegulationId){logger.send([{Level:'error',Message:'Error: regulationId undefined (from logindata)'}]);designatedRegulationId=1;}
if(!countryId){logger.send([{Level:'error',Message:'Error: countryId undefined (from logindata)'}]);countryId=0;}
window.eToroMarketingData.regulationId=designatedRegulationId;_this.setCookie(_this.config.cookieUserDesignatedRegulationName,designatedRegulationId,1);window.eToroMarketingData.countryId=countryId;_this.setCookie(_this.config.cookieUserCountryName,countryId,1);_this.inProgress=false;_this.run();}catch(e){logger.send([{Level:'warn',Url:httpUrl,Message:"logindata JSON parsing error",Exception:e}]);}});};EToroRegulationsService.prototype.setVisitorMarketingData=function(){let _this=this;let apiIP2RegulationURL='https://api.etoro.com/API/Internal/V1/IP2RegulationV2';if(_this.inProgress){return;}
_this.inProgress=true;const logger=_this.loggers['wp_etoro_site'];logger.http('GET',apiIP2RegulationURL,{'Ocp-Apim-Subscription-Key':'291966dcff2b47a4a1b41a68b1be2114'},'json',null,null,function(success,data){let userRegulationInfo=null;if(success){try{userRegulationInfo=JSON.parse(data.target.responseText);}catch(e){logger.send([{Level:'error',Message:'Error: parsing UserRegulation error',Url:apiIP2RegulationURL,Exception:e}]);}}
let regID=(userRegulationInfo&&userRegulationInfo.regulationId)?userRegulationInfo.regulationId:false;let countryId=(userRegulationInfo&&userRegulationInfo.countryId)?userRegulationInfo.countryId:false;if(!regID){logger.send([{Level:'error',Message:'Error: regulationId undefined'}]);regID=1;}
if(!countryId){logger.send([{Level:'error',Message:'Error: countryId undefined'}]);countryId=0;}
window.eToroMarketingData.regulationId=regID;_this.setCookie(_this.config.cookieVisitorRegulationName,regID,1);window.eToroMarketingData.countryId=countryId;_this.setCookie(_this.config.cookieVisitorCountryName,countryId,1);_this.inProgress=false;_this.run();});};EToroRegulationsService.prototype.getRegulationAndCountry=function(){let stsData=this.etoroUserLogin.getLoginData();let regulationId,countryId;if(window.eToroMarketingData.regulationId&&typeof window.eToroMarketingData.countryId==="number"){this.run();return;}
if(stsData&&stsData.accessToken&&!stsData.expired){regulationId=parseInt(this.getCookie(this.config.cookieUserDesignatedRegulationName),10);countryId=parseInt(this.getCookie(this.config.cookieUserCountryName),10);if(!isNaN(regulationId)){window.eToroMarketingData.regulationId=regulationId;}
if(!isNaN(regulationId)){window.eToroMarketingData.countryId=countryId;}
if(regulationId&&typeof countryId==="number"){this.run();}else{this.setUserMarketingData();}}else{regulationId=parseInt(this.getCookie(this.config.cookieVisitorRegulationName),10);countryId=parseInt(this.getCookie(this.config.cookieVisitorCountryName),10);if(!isNaN(regulationId)){window.eToroMarketingData.regulationId=regulationId;}
if(!isNaN(regulationId)){window.eToroMarketingData.countryId=countryId;}
if(regulationId&&typeof countryId==="number"){this.run();}else{this.setVisitorMarketingData();}}};